# Generated by Django 3.0.7 on 2020-06-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200625_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='on_click_purchasing',
            field=models.BooleanField(default=False),
        ),
    ]
