# Generated by Django 3.0.7 on 2020-12-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ssl_charge_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
